# Ident
ident: 'Logsandra Server 1'

# Web service
web_enabled: True
web_address: "0.0.0.0"
web_port: 5000
web_config: 'development.ini'

# Cassandra cluster to connect to 
cassandra_address: 'localhost'
cassandra_port: 9160
cassandra_timeout: 5

# List of paths (files and directories) to monitor
paths:
    - name: ~/coding/cassandra/access.log
      recursive: False
      parser: 'clf'
      clf_format: '%h %l %u %t %r %s %O %{Referer}i %{User-Agent}i'
