# Webservice
webservice_enabled: True
webservice_address: localhost
webservice_port: 8080

# Cassandra cluster to connect to 
cassandra_address: localhost
cassandra_port: 9160

# List of paths (files and directories) to monitor
paths:
    - name: ~/coding/cassandra/access.log
      recursive: False
      format: "%h %l %u %t %r %s %O %{Referer}i %{User-Agent}i"
